### ISSUE TITLE
v2.x throws "No tests were run"

### ISSUE THREAD

**Issue by XhmikosR** [karma-runner/karma-qunit#103]
Hello.

I tried to update karma-qunit to v2.x along with the necessary switch to `qunit` instead of `qunitjs` for Bootstrap.

I always end up with this:

```

HeadlessChrome 65.0.3325 (Windows 7.0.0) ERROR
  {
    "message": "Uncaught Error: No tests were run.\nat node_modules/qunit/qunit/qunit.js:1248:5\n\nError: No tests were
run.\n    at done (node_modules/qunit/qunit/qunit.js:1248:11)\n    at advanceTestQueue (node_modules/qunit/qunit/qunit.j
s:1144:5)\n    at Object.advance (node_modules/qunit/qunit/qunit.js:1113:5)\n    at begin (node_modules/qunit/qunit/quni
t.js:3126:20)\n    at node_modules/qunit/qunit/qunit.js:3086:6",
    "str": "Uncaught Error: No tests were run.\nat node_modules/qunit/qunit/qunit.js:1248:5\n\nError: No tests were run.
\n    at done (node_modules/qunit/qunit/qunit.js:1248:11)\n    at advanceTestQueue (node_modules/qunit/qunit/qunit.js:11
44:5)\n    at Object.advance (node_modules/qunit/qunit/qunit.js:1113:5)\n    at begin (node_modules/qunit/qunit/qunit.js
:3126:20)\n    at node_modules/qunit/qunit/qunit.js:3086:6"
  }
HeadlessChrome 65.0.3325 (Windows 7.0.0): Executed 0 of 0 ERROR (0.009 secs / 0 secs)
HeadlessChrome 65.0.3325 (Windows 7.0.0): Executed 0 of 0 ERROR (0.013 secs / 0 secs)
.
HeadlessChrome 65.0.3325 (Windows 7.0.0): Executed 1 of 0 ERROR (0.015 secs / 0 secs)
.
HeadlessChrome 65.0.3325 (Windows 7.0.0): Executed 2 of 0 ERROR (0.028 secs / 0 secs)
.
HeadlessChrome 65.0.3325 (Windows 7.0.0): Executed 3 of 0 ERROR (0.046 secs / 0.004 secs)
.
HeadlessChrome 65.0.3325 (Windows 7.0.0): Executed 4 of 0 ERROR (0.077 secs / 0.036 secs)
```

Going back to the latest karma-qunit 1.x with qunitjs, works fine.

Are we missing something?

/CC @Johann-S

**Comment by Johann-S** [comment]
I don't know what's failed in our Bootstrap config 🤔 but in karma-qunit we have integration test and it passed 🙄

**Comment by XhmikosR** [comment]
The thing is that it doesn't show any info apart from the qunit exception.

Anyway, I opened the issue just in case anyone else had a similar issue. It's a pity we are still stuck with 1.x. :/

**Comment by shwetankverma** [comment]
I am also facing the similar issue. 
karma-qunit version is - 2.0.1

**Comment by robcornelius** [comment]
+1 from my team. This is blocking us moving to qunit 2.x

**Comment by Johann-S** [comment]
I made a PR which fix that, but it's hard to contact an available mainteners 😟

**Comment by XhmikosR** [comment]
If we don't hear from them in a few days I'll just fork the project under
the twbs org and move forward with the fix.

**Comment by Johann-S** [comment]
I proposed myself to maintain this project but no answer from @dignifiedquire
