### ISSUE TITLE
Expected/Actual object values in test failure are reported as [object Object]

### ISSUE THREAD

**Issue by Krinkle** [karma-runner/karma-qunit#24]
```
Running "karma:main" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 40.0.2214 (Mac OS X 10.9.5)]: Connected on socket 0J5WxWegS9ILUIaPX3Fv with id 3146024
..
Chrome 40.0.2214 (Mac OS X 10.9.5) ve setDomAttributes FAILED
	whitelist affects removal/updating of attributes
	Expected: [object Object]
	Actual: [object Object]
	    at Object.<anonymous> (tests/ve.test.js:120:9)
	    at Object.Test.run (node_modules/qunitjs/qunit/qunit.js:903:28)
	    at node_modules/qunitjs/qunit/qunit.js:1032:11
	    at process (node_modules/qunitjs/qunit/qunit.js:591:24)
	    at begin (node_modules/qunitjs/qunit/qunit.js:636:2)
	    at node_modules/qunitjs/qunit/qunit.js:652:4
	
................................................................................
................................................................................
...........................
Chrome 40.0.2214 (Mac OS X 10.9.5): Executed 190 of 190 (1 FAILED) (12.644 secs / 12.476 secs)
```

The HTML page report of QUnit, as well as other tools such as [grunt-contrib-qunit](https://github.com/gruntjs/grunt-contrib-qunit/) use a more sensible stringification.

**Comment by Krinkle** [comment]
Patching `src/adapter.js` to call `QUnit.jsDump.parse` on the expected and actual value while concatenating strings for the result would satisfy this. Similar to [grunt-contrib-qunit.git:/phantomjs/bridge.js](https://github.com/gruntjs/grunt-contrib-qunit/blob/0b3e6230340e21faea2b7260355e36899b658af9/phantomjs/bridge.js#L25-L36). I was writing a PR but the tests need some attention to accommodate for it.

**Comment by craigmingtaozhang** [comment]
@Krinkle 's way works. Really need this feature :+1:

**Comment by trobertsonsf** [comment]
:+1:
